WebAppCore_Noticias/Controllers/MunicipiosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebAppCore_Noticias.Data;
using WebAppCore_Noticias.Models;
using WebAppCore_Noticias.Models.ViewModels;

namespace WebAppCore_Noticias.Controllers
{
    public class MunicipiosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MunicipiosController(ApplicationDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Municipio.ToListAsync());
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var municipio = await _context.Municipio.SingleOrDefaultAsync(m => m.Id == id);

            if (municipio == null)
            {
                return NotFound();
            }

            return View(municipio);
        }

        // GET: Municipios/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Municipios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MunicipioViewModels viewModels)
        {
            if (ModelState.IsValid)
            {
                var model = new Municipio();
                model.Nome = viewModels.Nome;
                model.Uf = viewModels.Uf;

                _context.Add(model);

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(viewModels);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)            
                return NotFound();            

            var municipio = await _context.Municipio.SingleOrDefaultAsync(m => m.Id == id);

            if (municipio == null)            
                return NotFound();            

            return View(municipio);
        }

        // POST: Municipios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, MunicipioViewModels viewModels)
        {
            if (id != viewModels.Id)            
                return NotFound();            

            if (ModelState.IsValid)
            {
                try
                {
                    var model = new Municipio();
                    model.Nome = viewModels.Nome;
                    model.Uf = viewModels.Uf;

                    _context.Update(model);

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MunicipioExists(viewModels.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(viewModels);
        }

        // GET: Municipios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)            
                return NotFound();            

            var municipio = await _context.Municipio.SingleOrDefaultAsync(m => m.Id == id);

            if (municipio == null)            
                return NotFound();
            
            return View(municipio);
        }

        // POST: Municipios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var municipio = await _context.Municipio.SingleOrDefaultAsync(m => m.Id == id);

            _context.Municipio.Remove(municipio);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private bool MunicipioExists(int id)
        {
            return _context.Municipio.Any(e => e.Id == id);
        }
    }
}

WebAppCore_Noticias/Controllers/NoticiasController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebAppCore_Noticias.Data;
using WebAppCore_Noticias.Models;
using WebAppCore_Noticias.Models.ViewModels;

namespace WebAppCore_Noticias.Controllers
{
    [Authorize(Roles = "Noticia")]
    public class NoticiasController : Controller
    {
        private ApplicationDbContext dbContext;
        public NoticiasController(ApplicationDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var listaNoticias = dbContext.Noticias.OrderByDescending(c => c.DataPublicacao);

            return View("Index", listaNoticias);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var viewModel = new NoticiaViewModels();
            viewModel.ListaCategorias = new SelectList(dbContext.Categorias.OrderBy(x => x.Descricao), "Id", "Descricao");
            viewModel.DataPublicacao = DateTime.Parse(DateTime.Now.ToString("d"), CultureInfo.CreateSpecificCulture("pt-BR"));

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(NoticiaViewModels viewModel)
        {
            if(ModelState.IsValid)
            {
                var model = new Noticia
                {
                    Titulo = viewModel.Titulo,
                    Autor = viewModel.Autor,
                    Corpo = viewModel.Corpo,
                    DataPublicacao = viewModel.DataPublicacao,
                    Destaque = viewModel.Destaque,
                    CategoriaId = viewModel.CategoriaId
                };

                dbContext.Add(model);
                await dbContext.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            //SE OCORRER ALGUM ERRO FICA NA TELA COM OS DADOS PREENCHIDOS
            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            var objNoticias = await dbContext.Noticias.SingleOrDefaultAsync(x => x.Id == id);

            if (id == null || objNoticias == null)
            {
                return NotFound();
            }

            var viewModel = new NoticiaViewModels();

            viewModel.ListaCategorias = new SelectList(dbContext.Categorias.OrderBy(x => x.Descricao), "Id", "Descricao");            

            viewModel.Id = objNoticias.Id;
            viewModel.Titulo = objNoticias.Titulo;
            viewModel.Autor = objNoticias.Autor;
            viewModel.Corpo = objNoticias.Corpo;
            viewModel.DataPublicacao = objNoticias.DataPublicacao;
            viewModel.Destaque = objNoticias.Destaque;
            viewModel.CategoriaId = objNoticias.CategoriaId;

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(NoticiaViewModels viewModel)
        {
            if (ModelState.IsValid)
            {
                var model = await dbContext.Noticias.SingleOrDefaultAsync(x => x.Id == viewModel.Id);

                model.Titulo = viewModel.Titulo;
                model.Autor = viewModel.Autor;
                model.Corpo = viewModel.Corpo;
                model.DataPublicacao = viewModel.DataPublicacao;
                model.Destaque = viewModel.Destaque;
                model.CategoriaId = viewModel.CategoriaId;

                dbContext.Update(model);

                await dbContext.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            //SE OCORRER ALGUM ERRO FICA NA TELA COM OS DADOS PREENCHIDOS
            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            var objNoticias = await dbContext.Noticias.SingleOrDefaultAsync(x => x.Id == id);

            if (id == null || objNoticias == null)
            {
                return NotFound();
            }

            return View(objNoticias);
        }

        [HttpPost]
        //[HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var objNoticias = dbContext.Noticias.SingleOrDefault(x => x.Id == id);

            dbContext.Remove(objNoticias);

            await dbContext.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

WebAppCore_Noticias/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Noticias - @ViewData["Title"]</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/datetimepicker/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css" />

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/ckeditor/ckeditor.js"></script>
    

    <script type="text/javascript" src="/lib/datetimepicker/moment/min/moment.min.js"></script>
    <script type="text/javascript" src="/lib/datetimepicker/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>


    @*<script src="//cdn.ckeditor.com/4.8.0/full/ckeditor.js"></script>*@


</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Noticias</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Inicio</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">Sobre</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contato</a></li>

                    @if (User.IsInRole("Menu"))
                    {
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Administrativo<span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">

                                @if (User.IsInRole("Categoria"))
                                {
                                    <li><a asp-area="" asp-controller="Categoria" asp-action="Index">Categoria</a></li>
                                }

                                @if (User.IsInRole("Noticia"))
                                {
                                    <li role="separator" class="divider"></li>
                                    <li><a asp-area="" asp-controller="Noticias" asp-action="Index">Noticias</a></li>
                                }

                                @if (User.IsInRole("Municipio"))
                                {
                                    <li role="separator" class="divider"></li>
                                    <li><a asp-area="" asp-controller="Municipios" asp-action="Index">Municipios</a></li>
                                }

                            </ul>
                        </li>
                    }

                </ul>

                @await Html.PartialAsync("_LoginPartial")

            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Noticias</p>
        </footer>
    </div>
    
    @RenderSection("Scripts", required: false)

</body>
</html>